CREATE TABLE contest(
DISTRICT_ID INT NOT NULL,
FOREIGN KEY (DISTRICT_ID)
REFERENCES districts(DISTRICT_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
CANDIDATE_NAME VARCHAR(100) NOT NULL,
CANDIDATE_PARTY INT NOT NULL,
FOREIGN KEY (CANDIDATE_PARTY)
REFERENCES party(PARTY_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
CANDIDATE_RESIDENCE VARCHAR(100),
PROVINCE_ID INT NOT NULL,
FOREIGN KEY (PROVINCE_ID)
REFERENCES province(PROVINCE_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
CANDIDATE_OCCUPATION_ENGLISH VARCHAR(100),
CANDIDATE_OCCUPATION_FRENCH VARCHAR(100),
VOTES INT NOT NULL,
CONTEST_NUMBER INT NOT NULL,
WON BOOLEAN NOT NULL,
VOTE_PERCENT FLOAT);
