create table parliament(
PARLIAMENT_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (PARLIAMENT_ID),
PARLIAMENT_TYPE_ID INT NOT NULL,
FOREIGN KEY (PARLIAMENT_TYPE_ID)
REFERENCES PARLIAMENT_TYPE(PARLIAMENT_TYPE_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
GOVERNING_PARTY INT NOT NULL,
FOREIGN KEY (GOVERNING_PARTY)
REFERENCES PARTY(PARTY_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
PARLIAMENT_NUMBER INT NOT NULL,
START_DATE DATE,
END_DATE DATE,
ELECTION_DATE DATE
);
