create table party_trans_39(
PARTY_ID INT NOT NULL,
FOREIGN KEY (PARTY_ID)
REFERENCES PARTY(PARTY_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
PARTY_ENGLISH VARCHAR(40) NOT NULL,
PARTY_FRENCH VARCHAR(40) NOT NULL);
