create table party(
PARTY_ID INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(PARTY_ID),
PARLIAMENT_TYPE_ID INT NOT NULL,
FOREIGN KEY (PARLIAMENT_TYPE_ID) 
REFERENCES PARLIAMENT_TYPE(PARLIAMENT_TYPE_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
PARTY_UNIQUE_NAME VARCHAR(100) NOT NULL,
PARTY_ENGLISH_NAME VARCHAR(100) NOT NULL,
PARTY_FRENCH_NAME VARCHAR(100) NOT NULL,
PARTY_ENGLISH_ABBR VARCHAR(50) NOT NULL,
PARTY_FRENCH_ABBR VARCHAR(50) NOT NULL,
PARTY_COLOUR VARCHAR(6));
