create table party_leader(
PARTY_ID INT NOT NULL,
FOREIGN KEY (PARTY_ID)
REFERENCES PARTY(PARTY_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
PARLIAMENT_ID INT NOT NULL,
FOREIGN KEY (PARLIAMENT_ID)
REFERENCES PARLIAMENT(PARLIAMENT_ID)
ON UPDATE NO ACTION ON DELETE NO ACTION,
LEADER_NAME VARCHAR(30) NOT NULL,
LEADER_NUMBER INT NOT NULL);

CREATE UNIQUE INDEX PARTY_LEADER_IDX1 ON party_leader(PARTY_ID, PARLIAMENT_ID, LEADER_NUMBER);
