create table province(
PROVINCE_ID INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(PROVINCE_ID),
PROVINCE_ENGLISH_NAME VARCHAR(30) NOT NULL, 
PROVINCE_FRENCH_NAME VARCHAR(30) NOT NULL,
PROVINCE_ENGLISH_ABBREVIATION VARCHAR(10) NOT NULL,
PROVINCE_FRENCH_ABBREVIATION VARCHAR(10) NOT NULL,
PROVINCE_SYMBOL VARCHAR(2) NOT NULL);
