create table contest_result (DISTRICT_ID INT, CANDIDATE_NAME VARCHAR(100));

INSERT INTO contest_result (DISTRICT_ID, CANDIDATE_NAME)
SELECT DISTRICT_ID, CANDIDATE_NAME FROM contest o 
WHERE DISTRICT_ID IN (SELECT DISTRICT_ID from districts where PARLIAMENT_ID = (SELECT PARLIAMENT_ID FROM parliament where PARLIAMENT_TYPE_ID = (SELECT PARLIAMENT_TYPE_ID FROM parliament_type where PARLIAMENT_TYPE='Federal') AND PARLIAMENT_NUMBER=41))
AND o.VOTES = (SELECT MAX(votes) FROM contest WHERE DISTRICT_ID = o.DISTRICT_ID);

update contest c SET WON = 1 
WHERE (c.DISTRICT_ID, c.CANDIDATE_NAME) IN  (select DISTRICT_ID, CANDIDATE_NAME from contest_result);

drop table contest_result;
