INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Newfoundland and Labrador','Terre-Neuve-et-Labrador','N.L.','T.-N.-L.','NL');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Prince Edward Island','Île-du-Prince-Édouard','P.E.I.','Î.-P.-É.','PE');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Nova Scotia','Nouvelle-Écosse','N.S.','N.-É.','NS');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('New Brunswick','Nouveau-Brunswick','N.B.','N.-B.','NB');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Quebec','Québec','Que.','Qc','QC');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Ontario','Ontario','Ont.','Ont.','ON');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Manitoba','Manitoba','Man.','Man.','MB');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Saskatchewan','Saskatchewan','Sask.','Sask.','SK');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Alberta','Alberta','Alta.','Alb.','AB');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('British Columbia','Colombie-Britannique','B.C.','C.-B.','BC');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Yukon','Yukon','Y.T.','Yn','YT');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Northwest Territories','Territoires du Nord-Ouest','N.W.T.','T.N.-O.','NT');
INSERT INTO province(PROVINCE_ENGLISH_NAME, PROVINCE_FRENCH_NAME,PROVINCE_ENGLISH_ABBREVIATION,PROVINCE_FRENCH_ABBREVIATION,PROVINCE_SYMBOL) VALUES
('Nunavut','Nunavut','Nun.','Nt','NU');
